/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq.tables.records;


import com.apischan.stanfytest.jooq.tables.Candidate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CandidateRecord extends TableRecordImpl<CandidateRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -2147359415;

    /**
     * Setter for <code>public.candidate.id</code>.
     */
    public CandidateRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.candidate.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.candidate.firstname</code>.
     */
    public CandidateRecord setFirstname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.candidate.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.candidate.lastname</code>.
     */
    public CandidateRecord setLastname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.candidate.lastname</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Candidate.CANDIDATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Candidate.CANDIDATE.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Candidate.CANDIDATE.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CandidateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CandidateRecord value2(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CandidateRecord value3(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CandidateRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CandidateRecord
     */
    public CandidateRecord() {
        super(Candidate.CANDIDATE);
    }

    /**
     * Create a detached, initialised CandidateRecord
     */
    public CandidateRecord(Integer id, String firstname, String lastname) {
        super(Candidate.CANDIDATE);

        set(0, id);
        set(1, firstname);
        set(2, lastname);
    }
}
