version: '2'

volumes:
  pg_data:

networks:
  jobs_rest_network:

services:
  postgres_jobs:
    build:
      context: ../stanfytest-db
    image: docker_posgresql
    container_name: postgres_jobs
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: jobsuser
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: jobsdb
    ports:
      - 12658:5432
    networks:
      jobs_rest_network:

  rest_jobs:
    build:
      context: ../stanfytest-rest
    image: docker_jobs_rest
    container_name: rest_jobs
    ports:
      - 8082:5050
    networks:
      jobs_rest_network:
    restart:
      always
