/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Candidate implements Serializable {

    private static final long serialVersionUID = -2141150960;

    private final Integer id;
    private final String  firstname;
    private final String  surname;

    public Candidate(Candidate value) {
        this.id = value.id;
        this.firstname = value.firstname;
        this.surname = value.surname;
    }

    public Candidate(
        Integer id,
        String  firstname,
        String  surname
    ) {
        this.id = id;
        this.firstname = firstname;
        this.surname = surname;
    }

    public Integer getId() {
        return this.id;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public String getSurname() {
        return this.surname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Candidate (");

        sb.append(id);
        sb.append(", ").append(firstname);
        sb.append(", ").append(surname);

        sb.append(")");
        return sb.toString();
    }
}
