/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CandidateSkill implements Serializable {

    private static final long serialVersionUID = -2006369261;

    private final Integer id;
    private final Integer candidateId;
    private final Integer skillId;

    public CandidateSkill(CandidateSkill value) {
        this.id = value.id;
        this.candidateId = value.candidateId;
        this.skillId = value.skillId;
    }

    public CandidateSkill(
        Integer id,
        Integer candidateId,
        Integer skillId
    ) {
        this.id = id;
        this.candidateId = candidateId;
        this.skillId = skillId;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getCandidateId() {
        return this.candidateId;
    }

    public Integer getSkillId() {
        return this.skillId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CandidateSkill (");

        sb.append(id);
        sb.append(", ").append(candidateId);
        sb.append(", ").append(skillId);

        sb.append(")");
        return sb.toString();
    }
}
