/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VacancySkill implements Serializable {

    private static final long serialVersionUID = 1890835939;

    private final Integer id;
    private final Integer vacancyId;
    private final Integer skillId;

    public VacancySkill(VacancySkill value) {
        this.id = value.id;
        this.vacancyId = value.vacancyId;
        this.skillId = value.skillId;
    }

    public VacancySkill(
        Integer id,
        Integer vacancyId,
        Integer skillId
    ) {
        this.id = id;
        this.vacancyId = vacancyId;
        this.skillId = skillId;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getVacancyId() {
        return this.vacancyId;
    }

    public Integer getSkillId() {
        return this.skillId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VacancySkill (");

        sb.append(id);
        sb.append(", ").append(vacancyId);
        sb.append(", ").append(skillId);

        sb.append(")");
        return sb.toString();
    }
}
