/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vacancy implements Serializable {

    private static final long serialVersionUID = -1541482889;

    private final Integer id;
    private final String  companyName;
    private final String  title;
    private final String  description;

    public Vacancy(Vacancy value) {
        this.id = value.id;
        this.companyName = value.companyName;
        this.title = value.title;
        this.description = value.description;
    }

    public Vacancy(
        Integer id,
        String  companyName,
        String  title,
        String  description
    ) {
        this.id = id;
        this.companyName = companyName;
        this.title = title;
        this.description = description;
    }

    public Integer getId() {
        return this.id;
    }

    public String getCompanyName() {
        return this.companyName;
    }

    public String getTitle() {
        return this.title;
    }

    public String getDescription() {
        return this.description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vacancy (");

        sb.append(id);
        sb.append(", ").append(companyName);
        sb.append(", ").append(title);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
