/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq;


import com.apischan.stanfytest.jooq.tables.Candidate;
import com.apischan.stanfytest.jooq.tables.CandidateSkill;
import com.apischan.stanfytest.jooq.tables.Skill;
import com.apischan.stanfytest.jooq.tables.Vacancy;
import com.apischan.stanfytest.jooq.tables.VacancySkill;
import com.apischan.stanfytest.jooq.tables.records.CandidateRecord;
import com.apischan.stanfytest.jooq.tables.records.CandidateSkillRecord;
import com.apischan.stanfytest.jooq.tables.records.SkillRecord;
import com.apischan.stanfytest.jooq.tables.records.VacancyRecord;
import com.apischan.stanfytest.jooq.tables.records.VacancySkillRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CandidateRecord, Integer> IDENTITY_CANDIDATE = Identities0.IDENTITY_CANDIDATE;
    public static final Identity<CandidateSkillRecord, Integer> IDENTITY_CANDIDATE_SKILL = Identities0.IDENTITY_CANDIDATE_SKILL;
    public static final Identity<SkillRecord, Integer> IDENTITY_SKILL = Identities0.IDENTITY_SKILL;
    public static final Identity<VacancyRecord, Integer> IDENTITY_VACANCY = Identities0.IDENTITY_VACANCY;
    public static final Identity<VacancySkillRecord, Integer> IDENTITY_VACANCY_SKILL = Identities0.IDENTITY_VACANCY_SKILL;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CandidateRecord, Integer> IDENTITY_CANDIDATE = createIdentity(Candidate.CANDIDATE, Candidate.CANDIDATE.ID);
        public static Identity<CandidateSkillRecord, Integer> IDENTITY_CANDIDATE_SKILL = createIdentity(CandidateSkill.CANDIDATE_SKILL, CandidateSkill.CANDIDATE_SKILL.ID);
        public static Identity<SkillRecord, Integer> IDENTITY_SKILL = createIdentity(Skill.SKILL, Skill.SKILL.ID);
        public static Identity<VacancyRecord, Integer> IDENTITY_VACANCY = createIdentity(Vacancy.VACANCY, Vacancy.VACANCY.ID);
        public static Identity<VacancySkillRecord, Integer> IDENTITY_VACANCY_SKILL = createIdentity(VacancySkill.VACANCY_SKILL, VacancySkill.VACANCY_SKILL.ID);
    }
}
