/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq;


import com.apischan.stanfytest.jooq.tables.Candidate;
import com.apischan.stanfytest.jooq.tables.CandidateSkill;
import com.apischan.stanfytest.jooq.tables.Skill;
import com.apischan.stanfytest.jooq.tables.Vacancy;
import com.apischan.stanfytest.jooq.tables.VacancySkill;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 30337789;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.candidate</code>.
     */
    public final Candidate CANDIDATE = com.apischan.stanfytest.jooq.tables.Candidate.CANDIDATE;

    /**
     * The table <code>public.candidate_skill</code>.
     */
    public final CandidateSkill CANDIDATE_SKILL = com.apischan.stanfytest.jooq.tables.CandidateSkill.CANDIDATE_SKILL;

    /**
     * The table <code>public.skill</code>.
     */
    public final Skill SKILL = com.apischan.stanfytest.jooq.tables.Skill.SKILL;

    /**
     * The table <code>public.vacancy</code>.
     */
    public final Vacancy VACANCY = com.apischan.stanfytest.jooq.tables.Vacancy.VACANCY;

    /**
     * The table <code>public.vacancy_skill</code>.
     */
    public final VacancySkill VACANCY_SKILL = com.apischan.stanfytest.jooq.tables.VacancySkill.VACANCY_SKILL;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CANDIDATE_ID_SEQ,
            Sequences.CANDIDATE_SKILL_ID_SEQ,
            Sequences.SKILL_ID_SEQ,
            Sequences.VACANCY_ID_SEQ,
            Sequences.VACANCY_SKILL_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Candidate.CANDIDATE,
            CandidateSkill.CANDIDATE_SKILL,
            Skill.SKILL,
            Vacancy.VACANCY,
            VacancySkill.VACANCY_SKILL);
    }
}
