/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.candidate_id_seq</code>
     */
    public static final Sequence<Long> CANDIDATE_ID_SEQ = new SequenceImpl<Long>("candidate_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.candidate_skill_id_seq</code>
     */
    public static final Sequence<Long> CANDIDATE_SKILL_ID_SEQ = new SequenceImpl<Long>("candidate_skill_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.skill_id_seq</code>
     */
    public static final Sequence<Long> SKILL_ID_SEQ = new SequenceImpl<Long>("skill_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.vacancy_id_seq</code>
     */
    public static final Sequence<Long> VACANCY_ID_SEQ = new SequenceImpl<Long>("vacancy_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.vacancy_skill_id_seq</code>
     */
    public static final Sequence<Long> VACANCY_SKILL_ID_SEQ = new SequenceImpl<Long>("vacancy_skill_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
