/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq.tables;


import com.apischan.stanfytest.jooq.Keys;
import com.apischan.stanfytest.jooq.Public;
import com.apischan.stanfytest.jooq.tables.records.CandidateSkillRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CandidateSkill extends TableImpl<CandidateSkillRecord> {

    private static final long serialVersionUID = -176669007;

    /**
     * The reference instance of <code>public.candidate_skill</code>
     */
    public static final CandidateSkill CANDIDATE_SKILL = new CandidateSkill();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CandidateSkillRecord> getRecordType() {
        return CandidateSkillRecord.class;
    }

    /**
     * The column <code>public.candidate_skill.id</code>.
     */
    public final TableField<CandidateSkillRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('candidate_skill_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.candidate_skill.candidate_id</code>.
     */
    public final TableField<CandidateSkillRecord, Integer> CANDIDATE_ID = createField("candidate_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.candidate_skill.skill_id</code>.
     */
    public final TableField<CandidateSkillRecord, Integer> SKILL_ID = createField("skill_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.candidate_skill</code> table reference
     */
    public CandidateSkill() {
        this("candidate_skill", null);
    }

    /**
     * Create an aliased <code>public.candidate_skill</code> table reference
     */
    public CandidateSkill(String alias) {
        this(alias, CANDIDATE_SKILL);
    }

    private CandidateSkill(String alias, Table<CandidateSkillRecord> aliased) {
        this(alias, aliased, null);
    }

    private CandidateSkill(String alias, Table<CandidateSkillRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CandidateSkillRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CANDIDATE_SKILL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CandidateSkill as(String alias) {
        return new CandidateSkill(alias, this);
    }

    /**
     * Rename this table
     */
    public CandidateSkill rename(String name) {
        return new CandidateSkill(name, null);
    }
}
