/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq.tables;


import com.apischan.stanfytest.jooq.Keys;
import com.apischan.stanfytest.jooq.Public;
import com.apischan.stanfytest.jooq.tables.records.CandidateRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Candidate extends TableImpl<CandidateRecord> {

    private static final long serialVersionUID = -1627448848;

    /**
     * The reference instance of <code>public.candidate</code>
     */
    public static final Candidate CANDIDATE = new Candidate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CandidateRecord> getRecordType() {
        return CandidateRecord.class;
    }

    /**
     * The column <code>public.candidate.id</code>.
     */
    public final TableField<CandidateRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('candidate_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.candidate.firstname</code>.
     */
    public final TableField<CandidateRecord, String> FIRSTNAME = createField("firstname", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.candidate.surname</code>.
     */
    public final TableField<CandidateRecord, String> SURNAME = createField("surname", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * Create a <code>public.candidate</code> table reference
     */
    public Candidate() {
        this("candidate", null);
    }

    /**
     * Create an aliased <code>public.candidate</code> table reference
     */
    public Candidate(String alias) {
        this(alias, CANDIDATE);
    }

    private Candidate(String alias, Table<CandidateRecord> aliased) {
        this(alias, aliased, null);
    }

    private Candidate(String alias, Table<CandidateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CandidateRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CANDIDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Candidate as(String alias) {
        return new Candidate(alias, this);
    }

    /**
     * Rename this table
     */
    public Candidate rename(String name) {
        return new Candidate(name, null);
    }
}
