/**
 * This class is generated by jOOQ
 */
package com.apischan.stanfytest.jooq.tables;


import com.apischan.stanfytest.jooq.Keys;
import com.apischan.stanfytest.jooq.Public;
import com.apischan.stanfytest.jooq.tables.records.VacancySkillRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VacancySkill extends TableImpl<VacancySkillRecord> {

    private static final long serialVersionUID = -1723299463;

    /**
     * The reference instance of <code>public.vacancy_skill</code>
     */
    public static final VacancySkill VACANCY_SKILL = new VacancySkill();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VacancySkillRecord> getRecordType() {
        return VacancySkillRecord.class;
    }

    /**
     * The column <code>public.vacancy_skill.id</code>.
     */
    public final TableField<VacancySkillRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('vacancy_skill_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.vacancy_skill.vacancy_id</code>.
     */
    public final TableField<VacancySkillRecord, Integer> VACANCY_ID = createField("vacancy_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.vacancy_skill.skill_id</code>.
     */
    public final TableField<VacancySkillRecord, Integer> SKILL_ID = createField("skill_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.vacancy_skill</code> table reference
     */
    public VacancySkill() {
        this("vacancy_skill", null);
    }

    /**
     * Create an aliased <code>public.vacancy_skill</code> table reference
     */
    public VacancySkill(String alias) {
        this(alias, VACANCY_SKILL);
    }

    private VacancySkill(String alias, Table<VacancySkillRecord> aliased) {
        this(alias, aliased, null);
    }

    private VacancySkill(String alias, Table<VacancySkillRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<VacancySkillRecord, Integer> getIdentity() {
        return Keys.IDENTITY_VACANCY_SKILL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VacancySkill as(String alias) {
        return new VacancySkill(alias, this);
    }

    /**
     * Rename this table
     */
    public VacancySkill rename(String name) {
        return new VacancySkill(name, null);
    }
}
